### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by aidiss** [remonlam/rpi-zero-arch#21]
I get the following message:
```error while loading shared libraries: libnl-genl-3.so.200: wrong ELF class: ELFCLASS64```

**Comment by aidiss** [comment]
@remonlam could you please suggest a solution? 
I found some posts that this error might occur when there is incompatibility between 32b and 64b versions. But in this repo I think everything is 64b?

**Comment by aidiss** [comment]
https://stackoverflow.com/questions/216000/gcc-error-wrong-elf-class-elfclass64

**Comment by OrvilleQ** [comment]
@aidiss The main issues is that network setting scripts don't install libnl as the platform you choose while download archlinuxarm package but always use aarch64. So you need to edit some scripts yourself or just install the right version of libnl from folder packages.

**Comment by OrvilleQ** [comment]
I think I'll try to make a pull requests later.(Who knows.)
