### ISSUE TITLE
functionFormatDisk not working on Sandisk microSD cards

### ISSUE THREAD

**Issue by juliankrieger** [remonlam/rpi-zero-arch#22]
Many Sandisk micro SD cards do not work with gparted.

Solution: Add option to format SD cards with fdisk instant, like so
```

{
 43     # dd if=/dev/zero of=/dev/$sdCard bs=105M count=1
 44     (
 45         echo o # Create a new empty DOS partition table
 46         echo n # Add a new partition
 47         echo p # Primary partition
 48         echo 1 # Partition number
 49         echo   # Accept default sector
 50         echo "+100m" # Make first sector 100 megabytes
 51         echo t # change partition type
 52         echo c # change tye into W95 FAT32 LBA
 53         echo n # new partition
 54         echo p # new primary partition
 55         echo 2 # partition number 2
 56         echo   # Second sector (Accept default: 1)
 57         echo   # Accept sector default size
 58         echo w # Write changes
 59     ) | sudo fdisk /dev/sdX
 60 
 61   } &> /dev/null
```

**Comment by remonlam** [comment]
Hi Julian, thanks for sharing. I never had this issue myself just to be curious what model are you using?
Could you create a PR with your fix?

Thanks!

**Comment by juliankrieger** [comment]
I'm using the SanDisk Ultra 16GB, but I had the same problem with the 64GB version too, recently. The problem was that the partitions made by gparted could not be mounted on any of my computers afterwards, even with exactly the same mkfs commands. After modifying the functionFormatDisk file with the Code above, I got it to work.

I'll look to clean up a bit and create a pull request when I get home, maybe even give the user the possibility to choose wether to use fdisk or gparted.

**Comment by juliankrieger** [comment]
It seems someone edited it already, I think you can close this issue now
