### ISSUE TITLE
Check if image is on local storage

### ISSUE THREAD

**Issue by remonlam** [remonlam/rpi-zero-arch#4]
Check if the ArchLinuxARM-rpi-latest.tar.gz is already downloaded on the local drive if so do not download it again

**Comment by remonlam** [comment]
and do not remove the file if the user want's to save it for later usage

**Comment by mhaddon** [comment]
https://github.com/remonlam/rpi-arch-builder/pull/8

it checks the hash of the downloaded file to ensure its up to date, if not the user can chose to use an out of date version

**Comment by remonlam** [comment]
@mhaddon thanks, just merged #8
