### ISSUE TITLE
Support sdcards

### ISSUE THREAD

**Issue by Yamakaky** [remonlam/rpi-zero-arch#9]
On my system, the sdcard is named mmcblk0 and the first partition is named mmcblk0p1, but the script assumes it to be named mmcblk01.

Also, https://github.com/remonlam/rpi-arch-builder/blob/dev/functions/functionFormatDisk.sh#L28-L29 overrides https://github.com/remonlam/rpi-arch-builder/blob/dev/functions/masterVariables.sh#L5-L6.

**Comment by remonlam** [comment]
Thanks, will fix this issue

**Comment by remonlam** [comment]
@Yamakaky it should be fixed, can you test it?

**Comment by Yamakaky** [comment]
Seems good, maybe you should also update the doc to reference mmcblkX. Did the sdcard appear as sdX on your system?

**Comment by remonlam** [comment]
Great, yeah maybe I need to make that part more easier to understand.
Yes it did, It was running CentOS inside a Fusion virtual machine.
